# Jekyll Defaults
title: dev log
description: A small and simple site to test out Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://filipeguerreiro.github.io/blueface/"
github: http://github.com/filipeguerreiro/blog
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: about
  url: /about/
- text: archives
  url: /archives/
- text: tags
  url: /tags/
