# Jekyll Defaults
title: 日葡日記
description: A journal on work, side projects and personal endeavors.
baseurl: "/blog" # the subpath of your site, e.g. /blog

url: "https://filipeguerreiro.github.io/blog"
github: http://github.com/filipeguerreiro/blog
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: about
  url: /about/
- text: archives
  url: /archives/
- text: tags
  url: /tags/
